
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

panel_custom:
  - name: example-panel
    # url_path needs to be unique for each panel_custom config
    url_path: redirect-server-controls
    sidebar_title: Example Panel
    sidebar_icon: mdi:server
    module_url: /local/example-panel.js
    config:
      # Data you want to make available to panel
      hello: world
  - name: recipe-panel-99
    # url_path needs to be unique for each panel_custom config
    url_path: recipes
    sidebar_title: Recipes
    sidebar_icon: mdi:map
    module_url: /local/recipe-panel-99.js
    config:
      # Data you want to make available to panel
      hello: world
  - name: ingredients-panel-15
    # url_path needs to be unique for each panel_custom config
    url_path: ingredients
    sidebar_title: Ingredients
    sidebar_icon: mdi:toaster-oven
    module_url: /local/ingredients-panel-15.js
    config:
      # Data you want to make available to panel
      hello: world
